spring:
  application:
    name: techblitz-storage-service
  servlet:
    multipart:
      max-file-size: 100MB
server:
  port: ${SERVER_PORT}
application:
  url: ${SERVER_URL}
  client-url: ${CLIENT_URL}
  allowed-image-extensions:
    - png
    - jpg
    - jpeg
    - webp
security:
  jwt:
    signin-key: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
