spring:
  application:
    name: techblitz-storage-service
  servlet:
    multipart:
      max-file-size: 100MB
server:
  port: ${SERVER_PORT}
application:
  url: ${SERVER_URL}
  allowed-image-extensions:
    - png
    - jpg
    - jpeg
    - webp
